-- Describe RESPUESTAS
CREATE TABLE respuestas (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT
    "ID_PREGUNTA" INTEGER,
    "TEXTO" TEXT,
    "CORRECTA" INTEGER DEFAULT ('0'),
     FOREIGN KEY (ID_PREGUNTA) references PREGUNTAS(ID) ON DELETE CASCADE
)

