-- Describe ALUMNOS_SENECA
CREATE TABLE alumnos_seneca (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "alumnoa" TEXT,
    "estadomatrcula" TEXT,
    "nidescolar" TEXT,
    "dnipasaporte" TEXT,
    "direccin" TEXT,
    "cdigopostal" TEXT,
    "localidadderesidencia" TEXT,
    "fechadenacimiento" TEXT,
    "provinciaderesidencia" TEXT,
    "telfono" TEXT,
    "telfonodeurgencia" TEXT,
    "correoelectrnico" TEXT,
    "curso" TEXT,
    "ndelexpedientedelcentro" TEXT,
    "unidad" TEXT,
    "primerapellido" TEXT,
    "segundoapellido" TEXT,
    "nombre" TEXT,
    "dnipasaporteprimerturor" TEXT,
    "primerapellidoprimertutor" TEXT,
    "segundoapellidoprimertutor" TEXT,
    "nombreprimertutor" TEXT,
    "sexoprimertutor" TEXT,
    "dnipasaportesegundotutor" TEXT,
    "primerapellidosegundotutor" TEXT,
    "segundoapellidosegundotutor" TEXT,
    "nombresegundotutor" TEXT,
    "sexosegundotutor" TEXT,
    "localidaddenacimiento" TEXT,
    "aodelamatrcula" TEXT,
    "ndematrculasenestecurso" TEXT,
    "observacionesdelamatrcula" TEXT,
    "provincianacimiento" TEXT,
    "pasdenacimiento" TEXT,
    "edada3112delaodematrcula" TEXT,
    "nacionalidad" TEXT,
    "sexo" TEXT
)
