pragma foreign_keys=ON;
---- Describe RESPUESTAS
CREATE TABLE "RESPUESTA" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_PREGUNTA" INTEGER,
    "TEXTO" TEXT,
    "CORRECTA" INTEGER,
     FOREIGN KEY (ID_PREGUNTA) references PREGUNTAS(ID) ON DELETE CASCADE
)
